name: Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build

    - uses: actions/upload-artifact@v3
      with:
        name: nam-java-bootstrapper-linux
        path: target/release/nam-java-bootstrapper